import type { Job, Course, School } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const jobs: Job[] = [
  {
    id: 'job-1',
    created_at: new Date().toISOString(),
    title: 'Software Engineer',
    company: 'Tech Solutions Inc.',
    location: 'Paris, France',
    salary: '€70,000 - €90,000',
    description: 'Develop and maintain web applications using modern technologies. Join a dynamic team in the heart of Paris.',
    travel_type: ['work'],
    apply_url: '#',
  },
  {
    id: 'job-2',
    created_at: new Date().toISOString(),
    title: 'Barista & Cafe Manager',
    company: 'The Cozy Corner Cafe',
    location: 'Tokyo, Japan',
    salary: '¥3,500,000 - ¥4,500,000',
    description: 'Manage daily cafe operations, train staff, and create a welcoming atmosphere for customers. Language skills are a plus.',
    travel_type: ['work', 'student'],
    apply_url: '#',
  },
  {
    id: 'job-3',
    created_at: new Date().toISOString(),
    title: 'Marketing Intern',
    company: 'Global Ventures',
    location: 'New York, USA',
    salary: 'Paid Internship',
    description: 'Assist the marketing team with social media campaigns, content creation, and market research. Great for students.',
    travel_type: ['student'],
    apply_url: '#',
  },
  {
    id: 'job-4',
    created_at: new Date().toISOString(),
    title: 'Tour Guide',
    company: 'Sydney Adventures',
    location: 'Sydney, Australia',
    salary: 'Competitive hourly rate',
    description: 'Lead tours around Sydney, sharing knowledge about landmarks and culture. Must be energetic and love people.',
    travel_type: ['work', 'vacation'],
    apply_url: '#',
  },
   {
    id: 'job-5',
    created_at: new Date().toISOString(),
    title: 'Frontend Developer',
    company: 'Innovate Digital',
    location: 'Paris, France',
    salary: '€65,000 - €85,000',
    description: 'Craft beautiful and responsive user interfaces for our international clients. Experience with React is required.',
    travel_type: ['work'],
    apply_url: '#',
  },
  {
    id: 'job-6',
    created_at: new Date().toISOString(),
    title: 'English Teacher',
    company: 'Tokyo Language Institute',
    location: 'Tokyo, Japan',
    salary: '¥3,000,000 - ¥4,000,000',
    description: 'Teach English to students of all ages. TEFL/TESOL certification preferred. A rewarding experience for students and professionals.',
    travel_type: ['work', 'student'],
    apply_url: '#',
  }
];

export const courses: Course[] = [
  {
    id: 'course-1',
    created_at: new Date().toISOString(),
    school_id: "paris-language-school",
    title: 'French Language Immersion',
    institution: 'Paris Language School',
    location: 'Paris, France',
    duration: '4 Weeks',
    description: 'An intensive course for beginners to learn French while living in Paris. Cultural activities included.',
    travel_type: ['student', 'vacation'],
    enroll_url: '#',
  },
  {
    id: 'course-2',
    created_at: new Date().toISOString(),
    school_id: "tokyo-culinary-arts",
    title: 'Introduction to Japanese Cuisine',
    institution: 'Tokyo Culinary Arts',
    location: 'Tokyo, Japan',
    duration: '2 Weeks',
    description: 'Learn the art of sushi, ramen, and more from master chefs in the culinary capital of the world.',
    travel_type: ['student', 'vacation'],
    enroll_url: '#',
  },
  {
    id: 'course-3',
    created_at: new Date().toISOString(),
    school_id: "nyc-business-school",
    title: 'Digital Marketing Bootcamp',
    institution: 'NYC Business School',
    location: 'New York, USA',
    duration: '12 Weeks',
    description: 'A comprehensive program covering SEO, SEM, social media marketing, and analytics. Prepares you for a career in tech.',
    travel_type: ['student', 'work'],
    enroll_url: '#',
  },
  {
    id: 'course-4',
    created_at: new Date().toISOString(),
    school_id: "sydney-marine-institute",
    title: 'Marine Biology Field Study',
    institution: 'Sydney Marine Institute',
    location: 'Sydney, Australia',
    duration: '6 Weeks',
    description: 'Explore the Great Barrier Reef and learn about marine conservation efforts in this hands-on course.',
    travel_type: ['student'],
    enroll_url: '#',
  },
];

export const schools: School[] = [
  {
    id: 'paris-language-school',
    created_at: new Date().toISOString(),
    name: 'Paris Language School',
    location: 'Paris',
    country: 'France',
    description: 'Immerse yourself in the French language and culture at our school located in the heart of Paris. We offer a variety of courses for all levels.',
    image_url: "https://images.unsplash.com/photo-1660412581401-35c4c869cc0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxwYXJpcyUyMHVuaXZlcnNpdHl8ZW58MHx8fHwxNzU4ODIzNjM5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    image_description: "A charming street in Paris with a view of a university building.",
    image_hint: "paris university",
    courses: [
        {
            id: 'course-1',
            created_at: new Date().toISOString(),
            school_id: 'paris-language-school',
            title: 'French Language Immersion',
            institution: 'Paris Language School',
            location: 'Paris, France',
            duration: '4 Weeks',
            description: 'An intensive course for beginners to learn French while living in Paris. Cultural activities included.',
            travel_type: ['student', 'vacation'],
            enroll_url: '#',
        },
    ],
  },
    {
    id: 'nyc-business-school',
    created_at: new Date().toISOString(),
    name: 'NYC Business School',
    location: 'New York',
    country: 'USA',
    description: 'Gain a competitive edge in the business world with our industry-focused programs in the financial capital of the world.',
    image_url: "https://images.unsplash.com/photo-1711157393411-1508c9e61067?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw5fHxuZXcteW9yayUyMHVuaXZlcnNpdHl8ZW58MHx8fHwxNzU4ODIzNjM5fDA&ixlib=rb-4.1.0&q=80&w=1080",
    image_description: "A modern university building in New York City.",
    image_hint: "new-york university",
    courses: [
        {
            id: 'course-3',
            created_at: new Date().toISOString(),
            school_id: 'nyc-business-school',
            title: 'Digital Marketing Bootcamp',
            institution: 'NYC Business School',
            location: 'New York, USA',
            duration: '12 Weeks',
            description: 'A comprehensive program covering SEO, SEM, social media marketing, and analytics. Prepares you for a career in tech.',
            travel_type: ['student', 'work'],
            enroll_url: '#',
        },
    ],
  },
  {
    id: 'tokyo-culinary-arts',
    created_at: new Date().toISOString(),
    name: 'Tokyo Culinary Arts',
    location: 'Tokyo',
    country: 'Japan',
    description: 'Master the art of Japanese cooking, from traditional techniques to modern gastronomy, in vibrant Tokyo.',
    image_url: "https://images.unsplash.com/photo-1713635632424-e5b0876abe5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx0b2t5byUyMGNhbXB1c3xlbnwwfHx8fDE3NTg4MjM2Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    image_description: "A university campus in Tokyo with cherry blossoms.",
    image_hint: "tokyo campus",
    courses: [
        {
            id: 'course-2',
            created_at: new Date().toISOString(),
            school_id: 'tokyo-culinary-arts',
            title: 'Introduction to Japanese Cuisine',
            institution: 'Tokyo Culinary Arts',
            location: 'Tokyo, Japan',
            duration: '2 Weeks',
            description: 'Learn the art of sushi, ramen, and more from master chefs in the culinary capital of the world.',
            travel_type: ['student', 'vacation'],
            enroll_url: '#',
        }
    ],
  },
  {
    id: 'toronto-film-school',
    created_at: new Date().toISOString(),
    name: 'Toronto Film School',
    location: 'Toronto',
    country: 'Canada',
    description: 'Launch your career in the film industry with our hands-on programs in one of North America\'s biggest film hubs.',
    image_url: "https://images.unsplash.com/photo-1724502555871-b4e079027344?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx0b3JvbnRvJTIwdW5pdmVyc2l0eXxlbnwwfHx8fDE3NTg4MjM2Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    image_description: "A university building in Toronto during autumn.",
    image_hint: "toronto university",
    courses: [],
  },
  {
    id: 'sydney-marine-institute',
    created_at: new Date().toISOString(),
    name: 'Sydney Marine Institute',
    location: 'Sydney',
    country: 'Australia',
    description: 'Study marine biology and conservation with direct access to Australia\'s unique marine ecosystems.',
    image_url: "https://images.unsplash.com/photo-1693872398294-93f419e6475a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxfHxzeWRuZXklMjB1bml2ZXJzaXR5fGVufDB8fHx8MTc1ODgyMzYzOXww&ixlibrb-4.1.0&q=80&w=1080",
    image_description: "A university campus near the coast in Sydney.",
    image_hint: "sydney university",
    courses: [
        {
            id: 'course-4',
            created_at: new Date().toISOString(),
            school_id: 'sydney-marine-institute',
            title: 'Marine Biology Field Study',
            institution: 'Sydney Marine Institute',
            location: 'Sydney, Australia',
            duration: '6 Weeks',
            description: 'Explore the Great Barrier Reef and learn about marine conservation efforts in this hands-on course.',
            travel_type: ['student'],
            enroll_url: '#',
        }
    ],
  },
];
