import type { Destination, Job, Course, School } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const destinations: Destination[] = [
  {
    id: 'paris',
    name: 'Paris, France',
    description: 'The city of love, art, and fashion. Explore iconic landmarks and charming streets.',
    image: PlaceHolderImages.find(img => img.id === 'dest-paris')!,
    attractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame Cathedral'],
  },
  {
    id: 'tokyo',
    name: 'Tokyo, Japan',
    description: 'A bustling metropolis where tradition meets futuristic technology. Experience vibrant culture and cuisine.',
    image: PlaceHolderImages.find(img => img.id === 'dest-tokyo')!,
    attractions: ['Shibuya Crossing', 'Tokyo Skytree', 'Senso-ji Temple'],
  },
  {
    id: 'sydney',
    name: 'Sydney, Australia',
    description: 'A vibrant city known for its yacht-studded harbor, iconic opera house, and beautiful beaches.',
    image: PlaceHolderImages.find(img => img.id === 'dest-sydney')!,
    attractions: ['Sydney Opera House', 'Harbour Bridge', 'Bondi Beach'],
  },
    {
    id: 'new-york',
    name: 'New York, USA',
    description: "The city that never sleeps. A melting pot of cultures, arts, and global commerce.",
    image: PlaceHolderImages.find(img => img.id === 'dest-new-york')!,
    attractions: ['Times Square', 'Statue of Liberty', 'Central Park'],
  },
  {
    id: 'rome',
    name: 'Rome, Italy',
    description: "The Eternal City, boasting millennia of history, art, and architectural masterpieces.",
    image: PlaceHolderImages.find(img => img.id === 'dest-rome')!,
    attractions: ['Colosseum', 'Vatican City', 'Trevi Fountain'],
  },
  {
    id: 'cairo',
    name: 'Cairo, Egypt',
    description: "A sprawling capital set on the Nile River, home to ancient wonders and a vibrant modern life.",
    image: PlaceHolderImages.find(img => img.id === 'dest-cairo')!,
    attractions: ['Pyramids of Giza', 'Khan el-Khalili', 'Egyptian Museum'],
  },
];

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'Software Engineer',
    company: 'Tech Solutions Inc.',
    location: 'Paris, France',
    salary: '€70,000 - €90,000',
    description: 'Develop and maintain web applications using modern technologies. Join a dynamic team in the heart of Paris.',
    travelType: ['work'],
    applyUrl: '#',
  },
  {
    id: 'job-2',
    title: 'Barista & Cafe Manager',
    company: 'The Cozy Corner Cafe',
    location: 'Tokyo, Japan',
    salary: '¥3,500,000 - ¥4,500,000',
    description: 'Manage daily cafe operations, train staff, and create a welcoming atmosphere for customers. Language skills are a plus.',
    travelType: ['work', 'student'],
    applyUrl: '#',
  },
  {
    id: 'job-3',
    title: 'Marketing Intern',
    company: 'Global Ventures',
    location: 'New York, USA',
    salary: 'Paid Internship',
    description: 'Assist the marketing team with social media campaigns, content creation, and market research. Great for students.',
    travelType: ['student'],
    applyUrl: '#',
  },
  {
    id: 'job-4',
    title: 'Tour Guide',
    company: 'Sydney Adventures',
    location: 'Sydney, Australia',
    salary: 'Competitive hourly rate',
    description: 'Lead tours around Sydney, sharing knowledge about landmarks and culture. Must be energetic and love people.',
    travelType: ['work', 'vacation'],
    applyUrl: '#',
  },
   {
    id: 'job-5',
    title: 'Frontend Developer',
    company: 'Innovate Digital',
    location: 'Paris, France',
    salary: '€65,000 - €85,000',
    description: 'Craft beautiful and responsive user interfaces for our international clients. Experience with React is required.',
    travelType: ['work'],
    applyUrl: '#',
  },
  {
    id: 'job-6',
    title: 'English Teacher',
    company: 'Tokyo Language Institute',
    location: 'Tokyo, Japan',
    salary: '¥3,000,000 - ¥4,000,000',
    description: 'Teach English to students of all ages. TEFL/TESOL certification preferred. A rewarding experience for students and professionals.',
    travelType: ['work', 'student'],
    applyUrl: '#',
  }
];

export const courses: Course[] = [
  {
    id: 'course-1',
    title: 'French Language Immersion',
    institution: 'Paris Language School',
    location: 'Paris, France',
    duration: '4 Weeks',
    description: 'An intensive course for beginners to learn French while living in Paris. Cultural activities included.',
    travelType: ['student', 'vacation'],
    enrollUrl: '#',
  },
  {
    id: 'course-2',
    title: 'Introduction to Japanese Cuisine',
    institution: 'Tokyo Culinary Arts',
    location: 'Tokyo, Japan',
    duration: '2 Weeks',
    description: 'Learn the art of sushi, ramen, and more from master chefs in the culinary capital of the world.',
    travelType: ['student', 'vacation'],
    enrollUrl: '#',
  },
  {
    id: 'course-3',
    title: 'Digital Marketing Bootcamp',
    institution: 'NYC Business School',
    location: 'New York, USA',
    duration: '12 Weeks',
    description: 'A comprehensive program covering SEO, SEM, social media marketing, and analytics. Prepares you for a career in tech.',
    travelType: ['student', 'work'],
    enrollUrl: '#',
  },
  {
    id: 'course-4',
    title: 'Marine Biology Field Study',
    institution: 'Sydney Marine Institute',
    location: 'Sydney, Australia',
    duration: '6 Weeks',
    description: 'Explore the Great Barrier Reef and learn about marine conservation efforts in this hands-on course.',
    travelType: ['student'],
    enrollUrl: '#',
  },
];

export const schools: School[] = [
  {
    id: 'paris-language-school',
    name: 'Paris Language School',
    location: 'Paris, France',
    country: 'France',
    description: 'Immerse yourself in the French language and culture at our school located in the heart of Paris. We offer a variety of courses for all levels.',
    image: PlaceHolderImages.find(img => img.id === 'school-paris')!,
    courses: [
        {
            id: 'course-1',
            title: 'French Language Immersion',
            institution: 'Paris Language School',
            location: 'Paris, France',
            duration: '4 Weeks',
            description: 'An intensive course for beginners to learn French while living in Paris. Cultural activities included.',
            travelType: ['student', 'vacation'],
            enrollUrl: '#',
        },
    ],
  },
    {
    id: 'nyc-business-school',
    name: 'NYC Business School',
    location: 'New York, USA',
    country: 'USA',
    description: 'Gain a competitive edge in the business world with our industry-focused programs in the financial capital of the world.',
    image: PlaceHolderImages.find(img => img.id === 'school-ny')!,
    courses: [
        {
            id: 'course-3',
            title: 'Digital Marketing Bootcamp',
            institution: 'NYC Business School',
            location: 'New York, USA',
            duration: '12 Weeks',
            description: 'A comprehensive program covering SEO, SEM, social media marketing, and analytics. Prepares you for a career in tech.',
            travelType: ['student', 'work'],
            enrollUrl: '#',
        },
    ],
  },
  {
    id: 'tokyo-culinary-arts',
    name: 'Tokyo Culinary Arts',
    location: 'Tokyo, Japan',
    country: 'Japan',
    description: 'Master the art of Japanese cooking, from traditional techniques to modern gastronomy, in vibrant Tokyo.',
    image: PlaceHolderImages.find(img => img.id === 'school-tokyo')!,
    courses: [
        {
            id: 'course-2',
            title: 'Introduction to Japanese Cuisine',
            institution: 'Tokyo Culinary Arts',
            location: 'Tokyo, Japan',
            duration: '2 Weeks',
            description: 'Learn the art of sushi, ramen, and more from master chefs in the culinary capital of the world.',
            travelType: ['student', 'vacation'],
            enrollUrl: '#',
        }
    ],
  },
  {
    id: 'toronto-film-school',
    name: 'Toronto Film School',
    location: 'Toronto, Canada',
    country: 'Canada',
    description: 'Launch your career in the film industry with our hands-on programs in one of North America\'s biggest film hubs.',
    image: PlaceHolderImages.find(img => img.id === 'school-toronto')!,
    courses: [],
  },
  {
    id: 'sydney-marine-institute',
    name: 'Sydney Marine Institute',
    location: 'Sydney, Australia',
    country: 'Australia',
    description: 'Study marine biology and conservation with direct access to Australia\'s unique marine ecosystems.',
    image: PlaceHolderImages.find(img => img.id === 'school-sydney')!,
    courses: [
        {
            id: 'course-4',
            title: 'Marine Biology Field Study',
            institution: 'Sydney Marine Institute',
            location: 'Sydney, Australia',
            duration: '6 Weeks',
            description: 'Explore the Great Barrier Reef and learn about marine conservation efforts in this hands-on course.',
            travelType: ['student'],
            enrollUrl: '#',
        }
    ],
  },
];
